language: shell
install: true
script:
  - 'JERVIS_SECRETS_TEST="${JERVIS_SECRETS_TEST:-if you see this then the test failed}"'
  - 'echo "Secret hidden on console: ${JERVIS_SECRETS_TEST}"'
jenkins:
  secrets_id: "jervis-secrets-test"
  secrets:
    JERVIS_SECRETS_TEST: 'RUZ9cwix8DStc9Nxy3iiNVhS0+3RvgZHQiFqRL9+U+LkJskD3fFNwvb3MfmU0LJQ/IbnW+FEEMizoJzUGpNWhw4mzpQgnr89gNP3eL5uD+d/bGpfYtilNFvxY1O1iyvVqp471Q5r9OLrdmj8SXXcl6x45YsqoNlnk2VxiONNap0ZQ1vu07QWCbxgDhTVpy3cueL9XYL1IFjDvfe8spXKUxSqmBcGtmay/HppdpJZlyb+bLX14NLEB5wCqZWb+TKMvO6XO16D/DWrdIhpxGhmmlDCYjNzg2HjnN3XcKSyi/s/VvuIRAiSqaQR/K4x4/1Enqo3K4jeNMkP/l2p0KoboA=='
